title: Mahathi Anand
description: Personal site
remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-include-cache

#URL settings -set these if you want absolute URLS
url: "https://mahathi-anand.github.io"  # Your live site URL
baseurl: ""  # Leave blank if this is a user/organization page

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

# Optional: defaults for pages and posts (useful to avoid repeating front matter)
defaults:
  -
    scope:
      path: ""  # all files
    values:
      layout: default
      author: Mahathi Anand

#Layout Options
# Enable sidebar navigation on left
navigation:
  - title: Home
    url: /
  - title: Biography
    url: /biography/
  - title: Curriculum Vitae
    url: /cv/
  - title: Research
    url: /research/
  - title: Projects
    url: /projects/
  - title: Publications
    url: /publications/
  - title: Contact
    url: /contact/

# Sidebar position
sidebar:
  position: left

  
