title: Mahathi Anand
description: Personal site
remote_theme: "mmistakes/minimal-mistakes"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-include-cache

url: "https://mahathi-anand.github.io"
baseurl: ""

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

# Use a skin to change default colors
minimal_mistakes_skin: dark  # or try 'dark', 'air', 'contrast', etc.

# Navigation links shown in sidebar
navigation:
  - title: Home
    url: /
  - title: Biography
    url: /biography/
  - title: Curriculum Vitae
    url: /cv/
  - title: Research
    url: /research/
  - title: Projects
    url: /projects/
  - title: Publications
    url: /publications/
  - title: Contact
    url: /contact/

# Enable sidebar navigation
defaults:
  -
    scope:
      path: ""
      type: pages
    values:
      layout: single
      sidebar:
        nav: "main"

# Optional custom author name
author: Mahathi Anand

