@import "custom"; // This imports assets/css/_custom.scss or .css

title: Mahathi Anand
description: Personal site
remote_theme: "mmistakes/minimal-mistakes"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-include-cache

url: "https://mahathi-anand.github.io"
baseurl: ""

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

# Use a skin to change default colors
minimal_mistakes_skin: dark  # or try 'dark', 'air', 'contrast', etc.

sidebar:
 position: left

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: single
      sidebar:
        nav: main
      style: custom
	


# Optional custom author name
author: Mahathi Anand

